### ISSUE TITLE
Readonly problem with Enhanced LOV Item (presumably on IG)

### ISSUE THREAD

**Issue by prosvet2** [Pretius/Pretius-APEX-Enhanced-Lov-Item#40]
Now, read/write mode seems to work on IG, too. The problem comes in the read only mode.
I have tried to reproduce the case in my Oracle APEX space. 

- Looks OK in RW mode
- Looks OK in RO mode when I use the plain vanilla Popup LOV on the child IG.
- In RO mode, when I use the Enhanced LOV Item on IG, I get the following message:
> Page protection violation: This can occur when you forward a page that has not yet fully loaded or when you manually modify protected page elements. Contact the application administrator for further assistance. 
![Capture](https://user-images.githubusercontent.com/14214855/71529456-17320f80-28e5-11ea-9604-316079e9c613.PNG)
 
It's enough to select a value in the main Enhanced LOV Item. 

workspace, user and pwd the same as in my email of 02.12.2019.

**Comment by bostrowski** [comment]
@prosvet2 
I have tested your example application and I was able to reproduce the issue on my local 5.1 APEX. I have investigated what could be causing the error and I think I have found the answer. I want to confirm it with Patrick Wolf/John Snyders before implementing the fix on github. 

I'm almost certain this is the fix:

in the beginning of render procedure add

```sql
    if p_param.value_set_by_controller and p_param.is_readonly then
      apex_debug.info(g_logprefix||' -> Item rendering aborted due to readonly and controller.');
      return;
    end if;
```

![image](https://user-images.githubusercontent.com/15342508/71589119-028f8a80-2b24-11ea-8de7-b1630f034af8.png)

This will prevent the plugin from rendering hidden input when it is used in interactive grid and it is in read-only state.
