### ISSUE TITLE
Getting "This page is asking you to confirm that you want to leave - data you have entered may not be saved" when navigating from page.

### ISSUE THREAD

**Issue by jxfireruby** [Pretius/Pretius-APEX-Enhanced-Lov-Item#44]
This occurs whenever I have a page item with your plugin as the type and if I select something anything from the plugin. This occurs even if the "Warn on Unsaved Changes" for the item is set to ignore. The warning does not occur if "Warn on Unsaved Changes" at the page level is set to no.

**Comment by bostrowski** [comment]
@jxfireruby

1. please reproduce the issue at apex.oracle.com
1. what version of the plugin you are using?

**Comment by jxfireruby** [comment]
I was using 1.0.4. I updated to 1.1.0 and the warning no longer appears when the item is set to ignore. Sorry for the inconvenience.
