### ISSUE TITLE
After upgrading apex to 19.2 we see that enhancedLOVItem plugin is unresponsive due to timeout

### ISSUE THREAD

**Issue by VenkatesuNallu** [Pretius/Pretius-APEX-Enhanced-Lov-Item#47]
We did upgrade our apex instance from APEX 19.1 to 19.2. After upgrading as suggested in https://einstein.oracle.com/apex/f?p=300000:10:113032395853106::NO:10:QUESTION:apex-pages-throws-uncaught-typeerror-enhancedlovitem-is-not-a-function-exception-in-apex-version-19-2-3490 did run ords validate.

After succ run of validate, the application was accessible without any issues. Now when we click on multiselect icon in one of our filter it just goes into recursion (which is evident from the browser console log) as below and timesout
`Error: Script terminated by timeout at:
trigger@http://cloudtracker-dev.vfarm.oraclecorp.com/i/libraries/apex/minified/desktop_all.min.js?v=19.2.0.00.18:2:69876
trigger/<@http://cloudtracker-dev.vfarm.oraclecorp.com/i/libraries/apex/minified/desktop_all.min.js?v=19.2.0.00.18:2:71222
each@http://cloudtracker-dev.vfarm.oraclecorp.com/i/libraries/apex/minified/desktop_all.min.js?v=19.2.0.00.18:2:2777
each@http://cloudtracker-dev.vfarm.oraclecorp.com/i/libraries/apex/minified/desktop_all.min.js?v=19.2.0.00.18:2:1419
trigger@http://cloudtracker-dev.vfarm.oraclecorp.com/i/libraries/apex/minified/desktop_all.min.js?v=19.2.0.00.18:2:71198
_popupClickOnCell@http://cloudtracker-dev.vfarm.oraclecorp.com/apex/apxcloudrm2/r/1050/files/plugin/177038449785711987/v110/enhancedLovItem.js:2067:13
a.widget/</h[b]</<@http://cloudtracker-dev.vfarm.oraclecorp.com/i/libraries/apex/minified/desktop_all.min.js?v=19.2.0.00.18:27:6847
i@http://cloudtracker-dev.vfarm.oraclecorp.com/i/libraries/apex/minified/deskt…`

Can you please help with this? We are not sure what has to be fixed here? It was all just working fine in APEX 19.1

**Comment by bostrowski** [comment]
@VenkatesuNallu 

It will be hard to guess what is the core of the issue without inspecting the implementation. 

1. Will it will be possible to reproduce the issue at apex.oracle.com on example data set (emp and dept)?
2. what version of the plugin you are using?
3. I can't access provided link due to security check after logging

![image](https://user-images.githubusercontent.com/15342508/74638919-2313b280-516d-11ea-8041-c202b6abe00b.png)

**Comment by VenkatesuNallu** [comment]
Thank you. We are using 1.0.4 version of this plugin. Yes this is not externally accessible link. i will see if i can reproduce it on apex.oracle.com

**Comment by bostrowski** [comment]
I suggest updating the plugin to recent release which is v1.1.0, or not yet released v1.1.1 (see branch).

See the changelog for v1.1.0 to learn about fixes. Your issue might be already fixed with a recent release.

![image](https://user-images.githubusercontent.com/15342508/74647476-00d56100-517c-11ea-8316-59f0449e1233.png)

**Comment by VenkatesuNallu** [comment]
This was all working fine with apex 19.1 but started seeing the issue with upgrading to 19.2 apex. So likely a compatibility issue?

**Comment by bostrowski** [comment]
Update the plugin and check if the issue still occurs. The current version of the plugin is v1.1.0.

**Comment by VenkatesuNallu** [comment]
Since we already have this enhancedLOVItem plugin 1.0.4 in the system, should we still follow the steps below to upgrade it to 1.1.0


    Install package APEX_ENHANCED_LOV_ITEM in Oracle APEX Schema
    Install the plugin file item_type_plugin_pl_ostrowskibartosz_apex_enhancedlovitem.sql

Can you also confirm how to execute these steps?

**Comment by bostrowski** [comment]
yes, you have to install the plugin and the package body again. 

In the case of the plugin APEX will override the existing instance in your application and in case of the package body use APEX SQL Workshop or SQL Developer. 

Same way as you have done with the first installation of the plugin.

**Comment by VenkatesuNallu** [comment]
After upgrading the plugin to 1.1.0 we are good .
