### ISSUE TITLE
How to add custom order by for LOV list

### ISSUE THREAD

**Issue by anjanappadg** [Pretius/Pretius-APEX-Enhanced-Lov-Item#50]
Hi,
Is there any way to add custom order by for LOV list. example table has currency column its should list USD first, EURO second, JPY third etc. 

ex : select currency code  as d, country_code  as r from currency_details 
order by (
    CASE currency_code
    
    WHEN 'USD'
    THEN 1
    
    WHEN 'EUR'
    THEN 2
    
    WHEN 'JPY'
    THEN 3
    
    WHEN 'GBP'
    THEN 4
    
    WHEN 'CAD'
    THEN 5
    
    WHEN 'AUD'
    THEN 6
    
    END
) ASC

**Comment by anjanappadg** [comment]
since above logic didn't work, its always list values by default asc order.

**Comment by bostrowski** [comment]
@anjanappadg 
I assume you are speaking about autocomplete.

Use `Settings \ Autocomplete Settings \ Use Custom Search Logic`. 

Detailed description available through Help Text in Page Designer.

**Comment by anjanappadg** [comment]
Thanks, I make changes its working fine in inline popup but  **not in modal dialog popup**, its listing default order only (asc). Even i tried with 'Report Columns Configuration' it didnt workout for me
**Inline dialog** 
<img width="375" alt="Screen Shot 2020-02-28 at 5 49 26 PM" src="https://user-images.githubusercontent.com/61578847/75548248-d6748500-5a52-11ea-9fc5-e0e49fcaa102.png">

**Modal dialog** 
<img width="461" alt="Screen Shot 2020-02-28 at 5 49 39 PM" src="https://user-images.githubusercontent.com/61578847/75548338-0d4a9b00-5a53-11ea-99d5-043aa26b23dd.png">

**Comment by VenkatesuNallu** [comment]
Hi bostrowski, Any pointers to this? We need to display the value in modal dialog popup too in the order that we need. am able to fix the issue with custom search in the inline dialog.

**Comment by bostrowski** [comment]
@VenkatesuNallu, @anjanappadg 

There is built-in option to set **default order in popup report** which is described in **help text** for attributes `Settings \ Popup Settings \ Report Columns Configuration` 

![image](https://user-images.githubusercontent.com/15342508/76201423-84222980-61f3-11ea-9f05-3c383167372d.png)

and `Settings \ Report Columns Configuration`

![image](https://user-images.githubusercontent.com/15342508/76201512-acaa2380-61f3-11ea-837c-62ce782e11a6.png)

Please read the docs at github and inline help text.

**Comment by VenkatesuNallu** [comment]
Well, thats exactly what my question is. In my case i dont want any sorting to happen on report column. Right now i have below under report column configuration, so my data gets sorted ascending on the column
{
  "defaultSort": {
    "column": "D",
    "direction": "asc"
  },
  "columns": {
    "D": {
      "heading": "Datacenter"
     }
  }
}

But what i would like to happen is no sorting to be applied here and display as its in the database since i want data to be displayed in a specific flow. But even if i dont specify anything it defaults to default sort and with the column as ascending.

**Comment by VenkatesuNallu** [comment]
I had also tried to update the report column configuration as below. Still it does not display as it is in dB and it sorts the values 
{
  "columns": {
    "D": {
      "heading": "Datacenter",
      "sort": false
     }
  }
}

**Comment by bostrowski** [comment]
use **rownum** as column to be default sort which won't be displayed in popup report.

Inspect item with sql query as

```sql
select 
  ename||' ('||rownum||')' d, 
  empno r, 
  rownum as db_default_sort 
from 
  emp
```

and the attribute set as
```json
{
  "defaultSort": {
    "column": "DB_DEFAULT_SORT",
    "direction": "asc"
  },
  "columns": {
    "D": {
      "heading": "Ename"
    }
  }
}
```

the result looks like this
![image](https://user-images.githubusercontent.com/15342508/76209826-1a118080-6203-11ea-85ed-467f84fc2eaa.png)

the sql query that fetched the data (from the plugin debug) looks like this

![image](https://user-images.githubusercontent.com/15342508/76209896-462d0180-6203-11ea-9a9a-aa37a1065604.png)

the default sort based on rownum is preserved
