### ISSUE TITLE
The Value  of "Display Null Value" is not showing in LOV box after search

### ISSUE THREAD

**Issue by anjanappadg** [Pretius/Pretius-APEX-Enhanced-Lov-Item#51]
Hi,
We have Services  LOV and  the Attributes "Display Null Value"  set to "ALL and Return value set to '0' (since its sql return 'R'  type is numeric). When we did search by  'ALL' its returns result but in LOV box showing empty value and selected value is disappeared. Its was working fine in previous version after upgraded to latest version it is not showing display value. 

Could you please help  us to resolve this issue

Service LOV :

<img width="302" alt="Screenshot 2020-03-31 at 11 18 44 PM" src="https://user-images.githubusercontent.com/61578847/78059574-b57fb680-73a7-11ea-8c81-cdc3e8c4fb1b.png">

Datacenter LOV:

<img width="311" alt="Screenshot 2020-03-31 at 11 29 38 PM" src="https://user-images.githubusercontent.com/61578847/78059600-bfa1b500-73a7-11ea-9a14-efe7aa7a685a.png">

Before Search :

<img width="1156" alt="Screenshot 2020-03-31 at 11 28 48 PM" src="https://user-images.githubusercontent.com/61578847/78059582-b9133d80-73a7-11ea-8fe6-02a61993e9d7.png">

After Search :
<img width="1177" alt="Screenshot 2020-03-31 at 11 29 05 PM" src="https://user-images.githubusercontent.com/61578847/78059587-badd0100-73a7-11ea-9285-1f81d1312aa4.png">

Search result with other then ALL
<img width="1155" alt="Screenshot 2020-03-31 at 11 41 24 PM" src="https://user-images.githubusercontent.com/61578847/78060600-72264780-73a9-11ea-89fb-843194b948f4.png">

Thanks,
Anjanappa

**Comment by bostrowski** [comment]
@anjanappadg 
Could you please write use case scenario step by step? I'm not sure I've understood the question. 

Please set similar configuration of the item but based on emp table at apex.oracle.com and send me login credentials (developer). It will be much easier to have shared enviroment.

**Comment by anjanappadg** [comment]
@bostrowski, Yes the null value is not showed after searching in autocomplete mode 
Here is apex.oracle.com login login credentials  and use-case steps
workspace : demoapx
user : anjanappa.gr@gmail.com
pass : qwerty123
App - Application 121813 - LOVTest -> Emp details

I done usecase scenario with PopLOV, Since am facing issue with APX_Enhanced_LOV  plugin
(Error in PLSQL code raised during plug-in processing.)

Steps
1. Open - Emp details page
2. Select 'ALL' and 'Name2' option in drop down and click search 
3. Check LOV model box displayed both "All and Name2" 
<img width="468" alt="Screenshot 2020-04-01 at 6 33 32 PM" src="https://user-images.githubusercontent.com/61578847/78140412-9afd1a00-7447-11ea-9113-246ba179dfbc.png">

The same use-case is not working in APX_Enhanced_LOV - on selecting  ex : All and Name2 after search, its show only Name2  and selected null (All) value is disappeared.

**Comment by bostrowski** [comment]
@anjanappadg 
In page designer I've navigated to app 121813 page 2. There is no item that uses my plugin

![image](https://user-images.githubusercontent.com/15342508/78141936-7d6e8700-742c-11ea-91e2-59eb39c94a6a.png)


I've navigated to Shared Components \ Plugins and I see that the plugin is installed but it is not used anywhere.

![image](https://user-images.githubusercontent.com/15342508/78141857-6334a900-742c-11ea-9e7c-07e93083d08a.png)

**Comment by anjanappadg** [comment]
@bostrowski, Yes i have installed plugin but when i used LOV plugin its throwing Error.
<img width="772" alt="Screenshot 2020-04-01 at 6 56 21 PM" src="https://user-images.githubusercontent.com/61578847/78142433-8ec68c00-744a-11ea-8646-d4bbb65c01be.png">

**Comment by anjanappadg** [comment]
<img width="468" alt="Screenshot 2020-04-01 at 6 33 32 PM" src="https://user-images.githubusercontent.com/61578847/78142648-ccc3b000-744a-11ea-8b0c-6f4398da2a00.png">

**Comment by anjanappadg** [comment]
<img width="650" alt="Screenshot 2020-04-01 at 6 58 29 PM" src="https://user-images.githubusercontent.com/61578847/78142685-da793580-744a-11ea-9463-7b3c6c04c138.png">

**Comment by bostrowski** [comment]
because you haven't installed the plugin package body. 

1. follow installation guide 
2. recreate use case
3. describe steps to reproduce the issue
4. let me know that the test enviroment is set
5. Please stop spamming comment with screenshots if you havent finished preparing test enviroment

**Comment by anjanappadg** [comment]
@bostrowski  Really sorry about attached screenshots and Thank you very much for reply. The issue in my side, i haven't installed  complete Plugin packages. So, after installing all packages its working fine.
Thank you again.

**Comment by bostrowski** [comment]
@anjanappadg 
what about the issue?

**Comment by anjanappadg** [comment]
The issue got resolved after installing APEX_ENHANCED_LOV_ITEM.plb. and APEX_ENHANCED_LOV_ITEM.sql  packages. Actually in our working environment we missed complete package installation. 
Thank you.

**Comment by anjanappadg** [comment]
It's Not a Bug
