### ISSUE TITLE
Apex Region display BLOB file

### ISSUE THREAD

**Issue by jbernal507** [Pretius/Pretius-APEX-Enhanced-Lov-Item#58]
Hi expert 
I have an pdf file storaged in BLOB column into Data Base... Its possible to create apex app to show the pdf file to end user, for example I can call application and pass parameter to open pdf I was looking some like embed.. but Im not sure to make automatically or I need to perform some click? 

thanks for your ideas..!

**Comment by bostrowski** [comment]
I'm closing the thread because its not related to the plug-in. 

Please ask such question at apex community forum.

Ps.
Yes it is possible.
