### ISSUE TITLE
What exactly is meant by "Oracle APEX Schema" ?

### ISSUE THREAD

**Issue by frankschmitt** [Pretius/Pretius-APEX-Enhanced-Lov-Item#59]
The installation instructions contain this sentence:

"Install package APEX_ENHANCED_LOV_ITEM in Oracle APEX Schema"

What *exactly* is the meaning of "Oracle APEX Schema" ? Is this the parsing schema of the application or the APEX_<apex_version> schema?

If the latter, might this have any negative consequences related to Oracle support? (as far as I know, you're not supposed to install anything in Oracle supplied schemata)

**Comment by bostrowski** [comment]
Hi @frankschmitt 

> What exactly is the meaning of "Oracle APEX Schema" ? Is this the parsing schema of the application or the APEX_<apex_version> schema?

The parsing schema is the schema that is used to parse application in.

from apex help

> Specifies the schema that all SQL and PL/SQL in the application will be parsed as. You may use #OWNER# to reference this value in SQL queries and PL/SQL (for example, in a region or a process).

You can check / change the current pasing schema in `Application Properties \ Security \ Database Session \ Parsing Schema`.

`APEX_<apex_version>` is db user that contains all APEX logic and yes, you shouldn't change it :-)

**Comment by frankschmitt** [comment]
Hi @bostrowski ,

then I'd suggest to change the README accordingly - replace 

"Install package APEX_ENHANCED_LOV_ITEM in Oracle APEX Schema"

with 

"Install package APEX_ENHANCED_LOV_ITEM in the parsing schema of your application"

I can create a PR if required.

**Comment by bostrowski** [comment]
No, it's not required, I will update the readme. Thank you for the feedback!
